
export const HEXAGRAM_GENERATE_KUA = 'HEXAGRAM_GENERATE_KUA';
export const HEXAGRAM_GENERATE_TRIGRAM = 'HEXAGRAM_GENERATE_TRIGRAM';
export const HEXAGRAM_GENERATE_HEXAGRAM = 'HEXAGRAM_GENERATE_HEXAGRAM';
export const HEXAGRAM_GENERATED = 'HEXAGRAM_GENERATED';
export const HEXAGRAM_CLEAR = 'HEXAGRAM_CLEAR';

export const REACT_APP_CLIENT_ID_IMGUR= 'Client-ID c58105c1612ff18';
export const REACT_APP_CLIENT_ID_GIPHY= 'P85PMs1e5hTKVwk3xGfLqNcvJOo6xqHZ'


